In [1]:
!pip install d2l==0.17.2

In [2]:
# Generating the Dataset
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
# Read the Dataset
def load_array(data_arrays, batch_size, is_train=True):
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [4]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[-0.7657008 , -0.81677645],
        [-1.2747585 ,  1.1931452 ],
        [ 0.27081472, -1.1552285 ],
        [ 0.3047912 , -1.1470214 ],
        [-2.0031152 , -1.2994035 ],
        [-1.6866826 ,  0.62357926],
        [ 0.17641433, -1.2878146 ],
        [ 1.2323617 ,  2.305823  ],
        [-2.1566    ,  0.486068  ],
        [ 0.1193871 , -1.2478296 ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 5.446871 ],
        [-2.4021518],
        [ 8.67507  ],
        [ 8.720598 ],
        [ 4.6163654],
        [-1.294836 ],
        [ 8.94295  ],
        [-1.1701393],
        [-1.7637663],
        [ 8.676416 ]], dtype=float32)>)

In [5]:
# Defining the Model
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [6]:
# Initializing Model Parameters
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [7]:
# Defining the Loss Function
loss = tf.keras.losses.MeanSquaredError()

In [8]:
# Defining the Optimization Algorithm
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [9]:
# Training
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000159
epoch 2, loss 0.000105
epoch 3, loss 0.000104


In [10]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([ 0.00059319 -0.00084496], shape=(2,), dtype=float32)
error in estimating b [-0.00032568]
